apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-ingress
  namespace: ns1-XXXXX  # Cambia esto por tu namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress

